name: HMT MultiPlatform Build

on: workflow_dispatch

jobs:
  build-webgl:
    name: Build for WebGL
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-action@v2
        with:
          version: 2020.3.32f1
          activate: true
          
      - name: Build WebGL
        run: |
          unity -batchmode -quit -projectPath $(pwd) -buildTarget WebGL -executeMethod BuildScript.BuildWebGL -logFile

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-action@v2
        with:
          version: 2020.3.32f1
          activate: true

      - name: Build Windows
        run: |
          unity -batchmode -quit -projectPath $(pwd) -buildTarget StandaloneWindows64 -executeMethod BuildScript.BuildWindows -logFile

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-action@v2
        with:
          version: 2020.3.32f1
          activate: true

      - name: Build Linux
        run: |
          unity -batchmode -quit -projectPath $(pwd) -buildTarget StandaloneLinux64 -executeMethod BuildScript.BuildLinux -logFile

  build-mac:
    name: Build for Mac
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-action@v2
        with:
          version: 2020.3.32f1
          activate: true

      - name: Build Mac
        run: |
          unity -batchmode -quit -projectPath $(pwd) -buildTarget StandaloneOSX -executeMethod BuildScript.BuildMac -logFile
